### PR TITLE
typing_extensions required only in py<3.8

### LINKED ISSUE #57: typing_extensions dependency Python < 3.8 selector
The upstream package has a Python < 3.8 selector on the `typing_extensions` dependency, which is not yet present in the feedstock. Should this be added or not? 

I've made a tentative PR to add it (#56), but closed it since it requires a rewrite from `noarch`. (I didn't fancy spending the time testing a non-`noarch` version of this package).

Edit: link to upstream dependency with selector: https://github.com/python/importlib_metadata/blob/v3.3.0/setup.cfg#L22.

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix #57

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
@conda-forge/core shouldn't the new recipe trigger builds for each Python version? AFAIU it is only building a package for Python 3.9.

Any suggestions?

**Comment by ocefpaf** [comment]
Those should be noarch and installable on any Python. Let me check...

**Comment by nicoddemus** [comment]
> Those should be noarch and installable on any Python. Let me check...

Ahh you mean https://github.com/conda-forge/importlib_metadata-feedstock/issues/57#issuecomment-744547572? OK thanks, if that is correct we can close this PR.

**Comment by ocefpaf** [comment]
> Ahh you mean [#57 (comment)](https://github.com/conda-forge/importlib_metadata-feedstock/issues/57#issuecomment-744547572)? OK thanks, if that is correct we can close this PR.

Yep. The selector is not used and the package should be installable on any Python. Can you confirm that?

**Comment by nicoddemus** [comment]
I installed `importlib-metadata` in Python 3.6 and 3.6:

```
λ conda create -n test-ilm-39 python=3.9 importlib-metadata=3.3
λ conda create -n test-ilm-36 python=3.6 importlib-metadata=3.3
```

In both environments we get `typing_extensions-3.7.4.3` and the actual module (`typing_extensions.py`), not a stub as mention in https://github.com/conda-forge/importlib_metadata-feedstock/issues/57#issuecomment-744547572.

This _might_ cause problems on some weird edge cases because that's how `importlib_metadat` imports it:

https://github.com/python/importlib_metadata/blob/a19e27bf8a1156ac3a60dfd274b83508e57223aa/importlib_metadata/_compat.py#L7-L15

So `importlib-metadata` in Python >=3.8 from conda-forge will always use `typing_extensions`, rather than `typing`. However, hypothetically this could also happen in other situations where `typing_extensions` might get been installed by some other package, so I think you are right in saying this is harmless. 

Should we close this and #57 then?

**Comment by ocefpaf** [comment]
> In both environments we get `typing_extensions-3.7.4.3` and the actual module (`typing_extensions.py`), not a stub as mention in [#57 (comment)](https://github.com/conda-forge/importlib_metadata-feedstock/issues/57#issuecomment-744547572).

This worries me a bit. Let's see what @bollwyvl has to say and, if we have to, let's remove the `noarch` from it.

**Comment by bollwyvl** [comment]
Sure, removing noarch seems like the correct thing to do if there are
conflicts.

**Comment by nicoddemus** [comment]
> Sure, removing noarch seems like the correct thing to do if there are
conflicts.

OK, thanks @ocefpaf and @bollwyvl.

So back to this PR: how can I build `importlib-metadata` for all Python versions? I already removed `noarch` and issued a rerender request, but that didn't do the trick. Anything else is needed?

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by nicoddemus** [comment]
Thanks @chrisburr! 👍

**Comment by nicoddemus** [comment]
Any reason why we don't have builds for Python 3.9 here? 🤔

**Comment by chrisburr** [comment]
As it was noarch it won't have been included in the Python 3.9 migration. As that migration is still active I think the bot would have picked it up after a few hours but I've done it by hand regardless.

**Comment by nicoddemus** [comment]
Thanks a lot folks!

**Comment by ocefpaf** [comment]
@chrisburr for the rescue! Thanks!!

**Pull request merged**
